### PR TITLE
Code review request

### PR DESCRIPTION
**Pull request by garethmullins**
@michealbradymahoney: Would you mind going through my code to review it? I'm interested in my naming scheme and usage of functions/methods.

### CODE REVIEW

**Comment by michealbradymahoney** [comment]
Hi Garath,
Sorry for the late reply. I'm not currently taking the subject so I wont be able to help.

Thanks,
Mick

Micheal Brady-Mahoney
Mentor Co-Leader for Information Technology
Co-President IT@JCU Students Association
Bachelor Information Technology Student

Office: BD017-050 – Ph: 4781 5844 (ext 15844)
micheal.bradymahoney@my.jcu.edu.au
Mobile: 0451 977 484

**Comment by garethmullins** [comment]
Ok, thanks for telling me

Get Outlook for iOShttps://aka.ms/o0ukef

**Comment by garethmullins** [comment]
@BradenRowlands: Would you mind going through my code to review it? I'm interested in my naming scheme and usage of functions/methods.

**Comment by BradenRowlands** [comment]
Hey Gareth,
Reading through your code made me realise how bad mine was haha.
I could not really find a lot that i would change or alter. The Usedcar was rather confusing to read but that was for testing the code.  Sorry i couldn't give you more feedback mate.

**Comment by garethmullins** [comment]
You had a look and found nothing that could be done better, so all's good, that's more then what some others have done.

**Pull request merged**
